/**
 * football.ts — reads the organism's football benchmark out of docs/fussball.html.
 *
 * This is the one scoreboard on the page that no language model can talk its
 * way out of: predictions are measured against real match results. The page is
 * regenerated by the heartbeat, so we parse it rather than duplicating numbers.
 */

export type Submission = {
  n: number
  name: string
  /** hit rate in percent */
  hit: number
  logloss: number
  /** signed distance to the baseline, as written by the organism */
  delta: string
  note: string
}

export type Football = {
  cards: { value: string; label: string }[]
  /** the dashed reference lines: bookmaker, baseline, always-home */
  refs: { label: string; value: number }[]
  rows: Submission[]
  footnote: string
  stand: string | null
  fetchedAt: number
}

const num = (s: string) => Number(s.replace('%', '').replace(',', '.').trim())

let cache: Promise<Football> | null = null
let cachedAt = 0

export function loadFootball(force = false): Promise<Football> {
  if (cache && !force && Date.now() - cachedAt < 9 * 60_000) return cache
  cachedAt = Date.now()
  cache = (async () => {
    const res = await fetch('./fussball.html?t=' + Math.floor(Date.now() / 60_000), { cache: 'no-store' })
    if (!res.ok) throw new Error(`fussball.html ${res.status}`)
    const doc = new DOMParser().parseFromString(await res.text(), 'text/html')

    const cards = [...doc.querySelectorAll('.karte')].map((el) => ({
      value: el.querySelector('.w')?.textContent?.trim() ?? '',
      label: el.querySelector('.l')?.textContent?.trim() ?? '',
    }))

    // "Buchmacher 51.5 %" → { label: 'Buchmacher', value: 51.5 }
    const refs = [...doc.querySelectorAll('svg text')]
      .map((t) => t.textContent?.trim() ?? '')
      .map((t) => t.match(/^(.+?)\s+([\d.,]+)\s*%$/))
      .filter((m): m is RegExpMatchArray => Boolean(m))
      .map((m) => ({ label: m[1]!.trim(), value: num(m[2]!) }))

    const rows: Submission[] = [...doc.querySelectorAll('table tbody tr')].map((tr) => {
      const c = [...tr.querySelectorAll('td')].map((td) => td.textContent?.trim() ?? '')
      return {
        n: Number(c[0] ?? 0),
        name: c[1] ?? '',
        hit: num(c[2] ?? '0'),
        logloss: num(c[3] ?? '0'),
        delta: c[4] ?? '',
        note: c[5] ?? '',
      }
    })

    const paragraphs = [...doc.querySelectorAll('main p')].map((p) => p.textContent?.replace(/\s+/g, ' ').trim() ?? '')
    const footnote = paragraphs.find((t) => /Gepr[üu]ft auf/.test(t)) ?? ''
    const stand = paragraphs.find((t) => /^Stand:/.test(t))?.replace(/^Stand:\s*/, '') ?? null

    return { cards, refs, rows, footnote, stand, fetchedAt: Date.now() }
  })()
  cache.catch(() => { cache = null })
  return cache
}
